# Problem 2
# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# Define vector to hold previously computed values
F <- rep(0, 33)

# Define function to compute Fibonacci numbers using memoization
fib <- function(n) {
    if(n <= 2) {
       return(1)
    }
    else if(F[n]>0) {
        return(F[n])
    }
    else {
       return(fib(n-1) + fib(n-2))
    }
}

# Compute the Fibonacci numbers
for(n in 1:33) {
    F[n] <- fib(n)
}

# Answer is 4613732
result <- sum(F[which(F%%2==0)])
cat("Sum of the even-valued terms whose values do not exceed four million:", 
    result)